apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJxdWF5LmlvIjp7InVzZX1hoRWduYkdVZVdIQ2tLdWNnTnlCSnlnR1ZqSm1GTzZoNmZHNnlQb04iLCJhdXRoIjoiY0Y5dFlYTmhiR0U2Y0ZGb1lrVjZZMGhCY0RacmRYZG9ZV1JXWVhaeWJsTmpXR2hGWjI1aVIxVmxWMGhEYTB0MVkyZE9lVUpLZVdkSFZtcEtiVVpQTm1nMlprYzJlVkJ2VGc9PSJ9fX0=
kind: Secret
metadata:
  name: container-registry-secret
type: kubernetes.io/dockerconfigjson
